// github.com/cawhitecode
// Chris White

// https://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// Answer: 4613732

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EvenFibonacciNumbers
{
    class Program
    {
        static void Main(string[] args)
        {
            int sum = 0;
            int[] fibNumbers = new int[] { 1, 2 };
            int newFib = 3;
            for (int x = 1; newFib < 4000000; x++)
            {
                newFib = fibNumbers[x - 1] + fibNumbers[x];
                fibNumbers = fibNumbers.Concat(new int[] { newFib }).ToArray();                
            }
            foreach (int number in fibNumbers)
            {
                if (number % 2 == 0)
                {
                    sum += number;
                }
            }
            Console.WriteLine(sum);
            Console.ReadLine();

        }
    }
}